// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACL3PIvQjRnMLNprEIacbRR-8WZxz1hNQ',
    appId: '1:318014479319:web:f8c6b75974ea005118c992',
    messagingSenderId: '318014479319',
    projectId: 'green-algeria-firebase',
    authDomain: 'green-algeria-firebase.firebaseapp.com',
    storageBucket: 'green-algeria-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANfqdn5R75og3UtTUTXuKFQ6Bad5p-RFQ',
    appId: '1:318014479319:android:a68a1d23cc60641118c992',
    messagingSenderId: '318014479319',
    projectId: 'green-algeria-firebase',
    storageBucket: 'green-algeria-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJi49cYZHCzn3GXK33DYadj2s8YLfsklQ',
    appId: '1:318014479319:ios:a9f4bfa57bed4e8618c992',
    messagingSenderId: '318014479319',
    projectId: 'green-algeria-firebase',
    storageBucket: 'green-algeria-firebase.firebasestorage.app',
    iosBundleId: 'com.saadisamir.greenAlgeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJi49cYZHCzn3GXK33DYadj2s8YLfsklQ',
    appId: '1:318014479319:ios:a9f4bfa57bed4e8618c992',
    messagingSenderId: '318014479319',
    projectId: 'green-algeria-firebase',
    storageBucket: 'green-algeria-firebase.firebasestorage.app',
    iosBundleId: 'com.saadisamir.greenAlgeria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACL3PIvQjRnMLNprEIacbRR-8WZxz1hNQ',
    appId: '1:318014479319:web:b876d2bbee2f18d218c992',
    messagingSenderId: '318014479319',
    projectId: 'green-algeria-firebase',
    authDomain: 'green-algeria-firebase.firebaseapp.com',
    storageBucket: 'green-algeria-firebase.firebasestorage.app',
  );

}