// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJ1IrLRb0IjyAFSkw8JQ_tC6MNVpVx00',
    appId: '1:177139315328:web:ed0a30ebef5f16dd21ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    authDomain: 'green-algeria-f0278.firebaseapp.com',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWC9vlgNmgPZJafFlxafMEOaa6FCYqlw',
    appId: '1:177139315328:android:e67b7072ba3ab18b21ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBafZ3zrXb3_GDVTt1SR-Yb-6E_8nxcEGo',
    appId: '1:177139315328:ios:97d1a0dac68bed2521ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
    androidClientId: '177139315328-8dqpc160dtk394qhq8ffrhvlt2def27j.apps.googleusercontent.com',
    iosClientId: '177139315328-9m36slfmvn3u72m17gfrfftbki09sfeb.apps.googleusercontent.com',
    iosBundleId: 'com.saadisamir.greenAlgeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBafZ3zrXb3_GDVTt1SR-Yb-6E_8nxcEGo',
    appId: '1:177139315328:ios:97d1a0dac68bed2521ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
    iosBundleId: 'com.saadisamir.greenAlgeria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCJ1IrLRb0IjyAFSkw8JQ_tC6MNVpVx00',
    appId: '1:177139315328:web:1a2419de487f6c2b21ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    authDomain: 'green-algeria-f0278.firebaseapp.com',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
  );
}