// File generated by FlutterFire CLI — corrected project: green-algeria-f0278
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Project: green-algeria-f0278 | Number: 177139315328
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWC9vlgNmgPZJafFlxafMEOaa6FCYqlw',
    appId: '1:177139315328:web:e67b7072ba3ab18b21ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    authDomain: 'green-algeria-f0278.firebaseapp.com',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWC9vlgNmgPZJafFlxafMEOaa6FCYqlw',
    appId: '1:177139315328:android:e67b7072ba3ab18b21ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWC9vlgNmgPZJafFlxafMEOaa6FCYqlw',
    appId: '1:177139315328:ios:97d1a0dac68bed2521ec65',  // FIX: correct iOS app ID
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
    iosBundleId: 'com.saadisamir.greenAlgeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWC9vlgNmgPZJafFlxafMEOaa6FCYqlw',
    appId: '1:177139315328:ios:97d1a0dac68bed2521ec65',  // FIX: correct macOS app ID (same as iOS)
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
    iosBundleId: 'com.saadisamir.greenAlgeria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWC9vlgNmgPZJafFlxafMEOaa6FCYqlw',
    appId: '1:177139315328:web:e67b7072ba3ab18b21ec65',
    messagingSenderId: '177139315328',
    projectId: 'green-algeria-f0278',
    authDomain: 'green-algeria-f0278.firebaseapp.com',
    storageBucket: 'green-algeria-f0278.firebasestorage.app',
  );
}